USE REGISTRO_SENA


CREATE TABLE COLORES 
(
	ID_COLORES INT PRIMARY KEY IDENTITY,
	COLORES VARCHAR(50),
	ID_COMPUTADOR INT REFERENCES COMPUTADORES (ID_COMPUTADOR),
    CREATE_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME
)


ALTER TABLE USUARIOS
ADD DOCUMENTOS INT;

ALTER TABLE USUARIOS
ADD CONTRASENA INT;

 EXEC sp_rename 'PERSONAS','DETALLE_PERSONAS';
