USE REGISTRO_SENA1


DROP TABLE HISTORIAL_USUARIO;

-- TIPO_DOCUMENTOS
EXEC sp_rename 'dbo.TIPO_DOCUMENTOS.CREATE_AT', 'FECHA_CREACION', 'COLUMN';
EXEC sp_rename 'dbo.TIPO_DOCUMENTOS.UPDATED_AT', 'FECHA_ACTUALIZACION', 'COLUMN';

-- PERSONAS
EXEC sp_rename 'dbo.PERSONAS.CREATE_AT', 'FECHA_CREACION', 'COLUMN';
EXEC sp_rename 'dbo.PERSONAS.UPDATED_AT', 'FECHA_ACTUALIZACION', 'COLUMN';

-- SEDES
EXEC sp_rename 'dbo.SEDES.CREATE_AT', 'FECHA_CREACION', 'COLUMN';
EXEC sp_rename 'dbo.SEDES.UPDATED_AT', 'FECHA_ACTUALIZACION', 'COLUMN';

-- JORNADAS
EXEC sp_rename 'dbo.JORNADAS.CREATE_AT', 'FECHA_CREACION', 'COLUMN';
EXEC sp_rename 'dbo.JORNADAS.UPDATED_AT', 'FECHA_ACTUALIZACION', 'COLUMN';

-- PROGRAMAS
EXEC sp_rename 'dbo.PROGRAMAS.CREATE_AT', 'FECHA_CREACION', 'COLUMN';
EXEC sp_rename 'dbo.PROGRAMAS.UPDATED_AT', 'FECHA_ACTUALIZACION', 'COLUMN';

-- FICHAS
EXEC sp_rename 'dbo.FICHAS.CREATE_AT', 'FECHA_CREACION', 'COLUMN';
EXEC sp_rename 'dbo.FICHAS.UPDATED_AT', 'FECHA_ACTUALIZACION', 'COLUMN';

-- ADMINISTRATIVOS
EXEC sp_rename 'dbo.ADMINISTRATIVOS.CREATE_AT', 'FECHA_CREACION', 'COLUMN';
EXEC sp_rename 'dbo.ADMINISTRATIVOS.UPDATED_AT', 'FECHA_ACTUALIZACION', 'COLUMN';

-- USUARIOS
EXEC sp_rename 'dbo.USUARIOS.CREATE_AT', 'FECHA_CREACION', 'COLUMN';
EXEC sp_rename 'dbo.USUARIOS.UPDATED_AT', 'FECHA_ACTUALIZACION', 'COLUMN';

-- APRENDICES
EXEC sp_rename 'dbo.APRENDICES.CREATE_AT', 'FECHA_CREACION', 'COLUMN';
EXEC sp_rename 'dbo.APRENDICES.UPDATED_AT', 'FECHA_ACTUALIZACION', 'COLUMN';

-- INSTRUCTORES
EXEC sp_rename 'dbo.INSTRUCTORES.CREATE_AT', 'FECHA_CREACION', 'COLUMN';
EXEC sp_rename 'dbo.INSTRUCTORES.UPDATED_AT', 'FECHA_ACTUALIZACION','COLUMN'

-- INGRESOS
EXEC sp_rename 'INGRESOS.CREATE_AT', 'FECHA_CREACION', 'COLUMN';
EXEC sp_rename 'INGRESOS.UPDATED_AT', 'FECHA_ACTUALIZACION', 'COLUMN';

-- SALIDAS
EXEC sp_rename 'SALIDAS.CREATE_AT', 'FECHA_CREACION', 'COLUMN';
EXEC sp_rename 'SALIDAS.UPDATED_AT', 'FECHA_ACTUALIZACION', 'COLUMN';

-- BIOMETRICAS
EXEC sp_rename 'BIOMETRICAS.CREATE_AT', 'FECHA_CREACION', 'COLUMN';
EXEC sp_rename 'BIOMETRICAS.UPDATED_AT', 'FECHA_ACTUALIZACION', 'COLUMN';

-- CARNETS
EXEC sp_rename 'CARNETS.CREATE_AT', 'FECHA_CREACION', 'COLUMN';
EXEC sp_rename 'CARNETS.UPDATED_AT', 'FECHA_ACTUALIZACION', 'COLUMN';

-- COMPUTADORES
EXEC sp_rename 'COMPUTADORES.CREATE_AT', 'FECHA_CREACION', 'COLUMN';
EXEC sp_rename 'COMPUTADORES.UPDATED_AT', 'FECHA_ACTUALIZACION', 'COLUMN';

-- COLORES
EXEC sp_rename 'COLORES.CREATE_AT', 'FECHA_CREACION', 'COLUMN';
EXEC sp_rename 'COLORES.UPDATED_AT', 'FECHA_ACTUALIZACION', 'COLUMN';

