CREATE DATABASE REGISTRO_SENA;
USE REGISTRO_SENA;

-- Tipos de documento
CREATE TABLE TIPO_DOCUMENTOS (
    ID_TIPDOC INT PRIMARY KEY IDENTITY,
    TIPO_DOCUMENTO VARCHAR(5) NOT NULL,
    CREATE_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME
);

-- Personas
CREATE TABLE PERSONAS (
    ID_PERSONA INT PRIMARY KEY IDENTITY,
    NOMBRE VARCHAR(25) NOT NULL,
    APELLIDO VARCHAR(30) NOT NULL,
    ID_TIPDOC INT REFERENCES TIPO_DOCUMENTOS(ID_TIPDOC),
    NUMERO_DOCUMENTO BIGINT UNIQUE NOT NULL,
    TELEFONO VARCHAR(25),
    CORREO_ELECTRONICO VARCHAR(50) UNIQUE,
    CREATE_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME
);

-- Sedes
CREATE TABLE SEDES (
    ID_SEDE INT PRIMARY KEY IDENTITY,
    NOMBRE_SEDE VARCHAR(50),
    DIRECCION VARCHAR(50),
    CREATE_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME
);

-- Jornadas
CREATE TABLE JORNADAS (
    ID_JORNADA INT PRIMARY KEY IDENTITY,
    NOMBRE_JORNADA VARCHAR(20),
    CREATE_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME
);

-- Programas de formación
CREATE TABLE PROGRAMAS (
    ID_PROGRAMA INT PRIMARY KEY IDENTITY,
    NOMBRE_PROGRAMA VARCHAR(50),
    CREATE_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME
);

-- Fichas
CREATE TABLE FICHAS (
    ID_FICHA INT PRIMARY KEY IDENTITY,
    NUMERO_FICHA VARCHAR(7) UNIQUE NOT NULL,
    ID_PROGRAMA INT REFERENCES PROGRAMAS(ID_PROGRAMA),
    ID_JORNADA INT REFERENCES JORNADAS(ID_JORNADA),
    CREATE_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME
);

-- Administrativos
CREATE TABLE ADMINISTRATIVOS (
    ID_ADMI INT PRIMARY KEY IDENTITY,
    ID_PERSONA INT REFERENCES PERSONAS(ID_PERSONA),
    CARGO VARCHAR(25),
    PLANTA VARCHAR(25),
    AREA VARCHAR(30),
    CREATE_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME
);

-- Usuarios (acceso al sistema)
CREATE TABLE USUARIOS (
    ID_USUARIO INT PRIMARY KEY IDENTITY,
    ID_PERSONA INT NOT NULL REFERENCES PERSONAS(ID_PERSONA),
    ESTADO BIT NOT NULL,
    ID_SEDE INT NOT NULL REFERENCES SEDES(ID_SEDE),
    ID_ADMI INT REFERENCES ADMINISTRATIVOS(ID_ADMI),
    ID_JORNADA INT REFERENCES JORNADAS(ID_JORNADA),
    CREATE_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME
);

-- Historial de cambios de usuario
CREATE TABLE HISTORIAL_USUARIO (
    ID_HISTORIAL INT PRIMARY KEY IDENTITY,
    ID_USUARIO INT NOT NULL REFERENCES USUARIOS(ID_USUARIO),
    CAMPO_MODIFICADO VARCHAR(50) NOT NULL,
    VALOR_ANTERIOR VARCHAR(100),
    VALOR_NUEVO VARCHAR(100),
    FECHA_CAMBIO DATETIME DEFAULT GETDATE(),
    MODIFICADO_POR INT REFERENCES USUARIOS(ID_USUARIO),
    OBSERVACIONES VARCHAR(255),
    CREATE_AT DATETIME DEFAULT GETDATE()
);

-- Aprendices
CREATE TABLE APRENDICES (
    ID_APRENDIZ INT PRIMARY KEY IDENTITY,
    ID_PERSONA INT REFERENCES PERSONAS(ID_PERSONA),
    ID_FICHA INT REFERENCES FICHAS(ID_FICHA),
    CREATE_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME
);

-- Instructores (ahora solo identifica a la persona como instructor)
CREATE TABLE INSTRUCTORES (
    ID_INSTRUCTOR INT PRIMARY KEY IDENTITY,
    ID_PERSONA INT UNIQUE NOT NULL REFERENCES PERSONAS(ID_PERSONA),
    CREATE_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME
);

-- Relación Instructor - Ficha (puede tener varias fichas)
CREATE TABLE INSTRUCTOR_FICHA (
    ID_INSTRUCTOR_FICHA INT PRIMARY KEY IDENTITY,
    ID_PERSONA INT NOT NULL REFERENCES PERSONAS(ID_PERSONA),
    ID_FICHA INT NOT NULL REFERENCES FICHAS(ID_FICHA),
    ID_JORNADA INT REFERENCES JORNADAS(ID_JORNADA),
    ID_SEDE INT REFERENCES SEDES(ID_SEDE),
    CREATE_AT DATETIME DEFAULT GETDATE()
);

-- Ingresos
CREATE TABLE INGRESOS (
    ID_INGRESO INT PRIMARY KEY IDENTITY,
    FECHA_INGRESO DATETIME DEFAULT GETDATE(),
    METODO_VERIFICACION VARCHAR(20),
    ID_USUARIO INT REFERENCES USUARIOS(ID_USUARIO),
    CREATE_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME
);

-- Salidas
CREATE TABLE SALIDAS (
    ID_SALIDA INT PRIMARY KEY IDENTITY,
    FECHA_SALIDA DATETIME DEFAULT GETDATE(),
    ID_USUARIO INT REFERENCES USUARIOS(ID_USUARIO),
    CREATE_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME
);

-- Registros biométricos
CREATE TABLE BIOMETRICAS (
    ID_BIOMETRICA INT PRIMARY KEY IDENTITY,
    ID_USUARIO INT REFERENCES USUARIOS(ID_USUARIO),
    CREATE_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME
);

-- Carnets
CREATE TABLE CARNETS (
    ID_CARNET INT PRIMARY KEY IDENTITY,
    NUMERO_CARNET INT UNIQUE,
    FECHA_EMISION DATE,
    ESTADO BIT,
    ID_USUARIO INT REFERENCES USUARIOS(ID_USUARIO),
    CREATE_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME
);

-- Computadores
CREATE TABLE COMPUTADORES (
    ID_COMPUTADOR INT PRIMARY KEY IDENTITY,
    CODIGO INT UNIQUE,
    MARCA VARCHAR(20),
    COLOR VARCHAR(15),
    ID_USUARIO INT REFERENCES USUARIOS(ID_USUARIO),
    CREATE_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME
);
